language: python
python:
  - "3.4"

before_install:
  - sudo bash linux_setup.sh

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - mysql -e "CREATE DATABASE elitetraderoutes CHARACTER SET utf8;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'elitetraderoutes'@'localhost' IDENTIFIED BY 'elitetraderoutespassword';" -uroot

# command to run tests
script:
  - bash project_setup.sh